---
name: Cleanup
on:
  schedule:
    # run every Saturday
    - cron: "0 12 * * 6"

jobs:
  clean:
    name: Clean stale packages and caches
    timeout-minutes: 10

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: percona-platform/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: percona-platform/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install tools
        run: make init

      - name: Clean node_modules cache
        run: |
          rm -rf node_modules
          git status
          git clean -xdn
